services:
  php-web:
    build: .
    container_name: php-web-docker-demo-sites
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.site1.rule=Host(`site1.localhost`)"
      - "traefik.http.routers.site1.entrypoints=web"
      - "traefik.http.routers.site2.rule=Host(`site2.localhost`)"
      - "traefik.http.routers.site2.entrypoints=web"
    volumes:
      - ./sites:/var/www/html
    expose:
      - "80"
  traefik:
    image: traefik:v2.10
    container_name: traefik-docker-demo-sites
    command:
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --api.insecure=true
    ports:
      - "80:80"
      - "8088:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/traefik.yml
  browsersync:
    image: node:20
    container_name: browsersync-docker-demo-sites
    working_dir: /app
    volumes:
      - ./sites:/app
    command: >
      sh -c "npm config set strict-ssl false &&
             npm install -g browser-sync &&
             browser-sync start --proxy 'php-web:80' --files '/app/**/*' --host '0.0.0.0' --port 3001 --no-open --no-ui"
    ports:
        - "3001:3001"